### PR TITLE
[Requirement-05-06-07]

### PR DESCRIPTION
**Pull request by IngridPaulino**

### CODE REVIEW

**Review by gabrielmorais-meli — APPROVED** [review]

**Review by amdzotelli — APPROVED** [review]
💯 💟

**Review by carolhakamada — APPROVED** [review]
❤️

**Review by marianasaraivameli — APPROVED** [review]
👍 ❤️

**Review by rosalia-oliveira — APPROVED** [review]
Aprovado para merge.

**Pull request merged**
